### ISSUE TITLE
Potential channel swap issue on mic_dual

### ISSUE THREAD

**Issue by ed-xmos** [xmos/lib_mic_array#113]
After DDR clock setup, if the time to reach the first input in the mic_array loop must not be longer than 32 x 2 = 64 6.144MHz clock periods, which is around 10.4us. This is 651 thread cycles at 62.5MHz. If it does then there is a chance of channel swapping due to the 3.072MHz mic clock being out of synch with the 6.144MHz capture clock. The overall timing will be dependent on the time delay, which is dependent on the code being called and how fast the thread is.

https://github.com/xmos/lib_mic_array/blob/master/lib_mic_array/src/mic_array_dual.xc#L353

The startup code in mic_dual_pdm_rx_decimate has several large memsets which will certainly push it over 650 thread cycles so this is a bug.

To remedy this, we could make all of the delay lines and state global (zeroed at c startup) or remove initialisation (glitch for short time). Either way, we need to document the timing constraint between clock setup and starting mic_dual_pdm_rx_decimate.

**Comment by oscarbailey-xmos** [comment]
Tested the timing of initialisation in `mic_dual_pdm_rx_decimate`:
Current init time: 3028 (timer ticks @ 100 MHz)
init time with static variables: 268 (timer ticks @ 100 MHz)

Running unit tests in #114

**Comment by oscarbailey-xmos** [comment]
Could not replicate this issue, tried artificially increasing the init time - if the mics were to swap, they would swap when 16 ticks were added to the init time after the initial 2 * 32 * 6.144 MHz cycles period.
Results of testing: https://xmosjira.atlassian.net/wiki/spaces/~839422671/pages/1894252877/Mic+swapping+issue
