### ISSUE TITLE
Standup GitHub Actions CI

### ISSUE THREAD

**Issue by keithm-xmos** [xmos/lib_mic_array#166]
Include:

- [x] Documentation build
- [ ] Code build
- [ ] Tests
  - [x] building
  - [ ] unit (run in GH Actions using xsim)
  - [ ] signal (run on HW at first)

**Comment by keithm-xmos** [comment]
Currently blocked because demos and tests will not build outside the context of the SDK.  Waiting for resolution.

**Comment by keithm-xmos** [comment]
Resolved by the creation of https://github.com/xmos/fwk_io

**Comment by xross** [comment]
GH Actions no longer used.
