### ISSUE TITLE
Missing deinterleave16()

### ISSUE THREAD

**Issue by astewart-xmos** [xmos/lib_mic_array#192]
@jcarrier-xmos pointed out to me that there is no implementation for `mic_array::deinterleave_pdm_samples<16>`, as there are for 
`mic_array::deinterleave_pdm_samples<8>`, `mic_array::deinterleave_pdm_samples<4>`, and `mic_array::deinterleave_pdm_samples<2>`.

`mic_array::deinterleave_pdm_samples<16>` is the function that should be used to take a block of PDM samples received on a port, with all the channels interleaved, and deinterleave them, so that each output word has samples from only one of the channels.

This is needed to support a 16 channel mic array instance.

**Comment by ed-xmos** [comment]
https://xmosjira.atlassian.net/jira/software/projects/AP/issues/AP-12?jql=project%20%3D%20%22AP%22%20AND%20text%20~%20%22mic%22%20ORDER%20BY%20created%20DESC
