### ISSUE TITLE
Legacy tests not yet working

### ISSUE THREAD

**Issue by ed-xmos** [xmos/lib_mic_array#202]
See https://github.com/xmos/lib_mic_array/blob/develop/.github/scripts/build_test_apps.sh

This is just a test to build using xcommon which fails:

```
modules/mic_array/build.xcore:feature/filter_design_test$ make tests-legacy_build
[100%] Building legacy_build.xe...
Checking build modules
Checking https://www.xmos.com for required libraries
ERROR: No compatible version found for lib_xcore_math.
/Applications/XMOS_XTC_15.2.1/build/xcommon/module_xcommon/build/../build/Makefile.common1:565: *** Missing build modules. Cannot continue.  
```

However, given our move away from xcommon, I'd say this is quite low priority.

**Comment by mbanth** [comment]
Closing since we're moving away from using xcommon in favour of cmake.
