### ISSUE TITLE
Two instances of p[FFT_N] blow up the memory

### ISSUE THREAD

**Issue by ThomasGmeinder** [xmos/lib_mic_array#29]
This commit introduces two instances of p[FFT_N]:
https://github.com/xmos/lib_mic_array/commit/f8b2735075c2f85725f1b0c0c0d287f3be9b2ef6

This causes two instances of p[FFT_N] in memory which exceeds the memory for this configuration:

#define MIC_ARRAY_WORD_LENGTH_SHORT 1
#define MIC_ARRAY_MAX_FRAME_SIZE_LOG2 12 

Error:  Memory available:       262144,   used:      288752 .  FAILED

Using a single instance of p[FFT_N] fits into memory:
  Memory available:       262144,   used:      255896 .  OKAY

Note: This has to be set to:
int your_favourite_window_function(unsigned i, unsigned window_length){
    return INT_MAX;
}

I will fix this with the next pull request

**Comment by andrewstanfordjason** [comment]
This is surely a bug in the compiler then.
