### ISSUE TITLE
Instructions for changing coefs not working

### ISSUE THREAD

**Issue by ThomasGmeinder** [xmos/lib_mic_array#35]
I changed the sampling rate from 48kHz to 16kHz following chapter 
10 Four Channel Decimator
in
http://intranet/projects/tools/BuildbotApps/lib_mic_array_3.0.0d18963e33ea.pdf

I noticed that this is not working: 
Set this to FIR_LUT(d) where d is the output_decimation_factor; FIR_LUT() is defined in fir_decimator.h.

I get this error:
../src/app_add_block_processing.xc:17:10: fatal error: 'fir_decimator.h' file not found
#include "fir_decimator.h"
         ^
../src/app_add_block_processing.xc:101:40: error: unknown function identifier `FIR_LUT' (possibly missing prototype?)
               THIRD_STAGE_DIV_FIR, 0, FIR_LUT(6),

**Comment by andrewstanfordjason** [comment]
tried doing a clean?

**Comment by ThomasGmeinder** [comment]
clean doesn't help. There seem to be two problems:
fir_decimator.h doesn't exist
FIR_LUT is not declared

**Comment by andrewstanfordjason** [comment]
I think you might be in a cross between v2 and v3 then
fir_decimator.h was replaced with fir_coefs.h in v3

**Comment by ThomasGmeinder** [comment]
Nope. My fork is up to date with the latest from upstream.
Therefore I conclude that the index.rst needs updating to replace fir_decimator.h with fir_coefs.h
But this issue will remain: fir_coefs.h does not declare FIR_LUT

**Comment by andrewstanfordjason** [comment]
Right, thanks. I'll look into that then.

**Comment by andrewstanfordjason** [comment]
Just pushed the doc fix.
