### ISSUE TITLE
mic_array_decimate_to_pcm_4ch() corrupting memory

### ISSUE THREAD

**Issue by astew** [xmos/lib_mic_array#39]
In the project I'm currently working on, I have a task which owns a block of memory. At the beginning of each loop, I zero out this block of memory via `memset()`. I noticed when debugging my project that almost immediately after calling `memset()` (before I wrote anything else to it), part of my memory was no longer zeroed.

After spending a good bit of time drilling down, I believe I've discovered the culprit: `mic_array_decimate_to_pcm_4ch()`.

The offending line of code is `decimate_to_pcm_4ch.S` line `826` ( which calls the `SAVE_SAMPLES_NORMAL()` macro). Every time this line is executed, it writes to the next word in my memory block.

I suspect this may be responsible for a range of problems I've periodically encountered, including data corruption, unexpected runtime exceptions, and sometimes code that just seems to quietly fail. The location at which is writes to memory is consistent with a given image, but small changes in code cause it to write to different places in memory (presumably due to symbol placement).

**Comment by astew** [comment]
Likely relevant...
I did a `xobjdump --syms` on my binary, and I noticed that I have a symbol
`comp.static` at address `0x00049ce8` which is `0x00004860` bytes long, and `spectrum_doubles` (my memory which was being overwritten) is at address `0x0004e548` -- directly after `comp.static`.

`comp.static` is the frame buffer array which I pass to `mic_array_init_time_domain_frame()`. Seeing that they're adjacent in memory, I suspected that I may have somehow been telling `lib_mic_array` that I have more frame buffers than I really have.. but that does not appear to be the case:


        //MIC_ARRAY_MAX_FRAME_SIZE_LOG2 = 9
        //DECIMATION_FACTOR = 6
        //FIR_COMPENSATOR_DIV_6 = 385980920
        //NUM_FRAME_BUFFERS = 3
        //DECIMATOR_COUNT = 1
        static mic_array_frame_time_domain comp[NUM_FRAME_BUFFERS];
        mic_array_decimator_conf_common_t dcc = {
                MIC_ARRAY_MAX_FRAME_SIZE_LOG2,
                1,
                0, 
                NULL,
                DECIMATION_FACTOR,
                g_third_stage_div_6_fir,
                16,
                FIR_COMPENSATOR_DIV_6*4,
                DECIMATOR_HALF_FRAME_OVERLAP,
                NUM_FRAME_BUFFERS
        };

        mic_array_decimator_config_t dc[DECIMATOR_COUNT] = {
                {&dcc, data[0], {INT_MAX, INT_MAX, INT_MAX, INT_MAX}, 4}
        };

        mic_array_decimator_configure(c_ds_output, DECIMATOR_COUNT, dc);

        mic_array_init_time_domain_frame(c_ds_output, DECIMATOR_COUNT, buffer, comp, dc);

Nothing obvious (to me) is wrong with this configuration -- it is the same one that I pass to `mic_array_get_next_time_domain_frame()`

**Comment by astew** [comment]
Okay, so I believe I've solved it.

Not shown in my previous comment is that `MIC_ARRAY_NUM_MICS`, defined in `mic_array_conf.h` is `3`, because we're only actually using 3 microphones. The frame buffers allocated above rely on `MIC_ARRAY_NUM_MICS` to allocate enough space for the data, which I was not doing.

There's still a potential issue here, though. I tried changing my decimator configuration to only use 3 channels. When I did that, my memory block was no longer overwritten with microphone data, but is instead overwritten with zeros.

`MIC_ARRAY_NUM_MICS` has to be `4`, because `SAVE_SAMPLES_NORMAL `(called at [`decimate_to_pcm_4ch.S:826`](https://github.com/xmos/lib_mic_array/blob/master/lib_mic_array/src/decimate_to_pcm_4ch.S#L826) always does 4 word writes.

Our work-around will have to be to always request 4 channels, but to only use 3 of them.

As a fix, I suggest a run-time assertion when initializing decimators to disallow any fewer than 4 microphones to be used. Clear documentation in the `mic_array.h` comments would also help to avoid others encountering this issue in the future.

**Comment by ed-xmos** [comment]
Thanks for reporting and following up on this. Yes, the IP has been optimised (at ASM level) for 4 blocks of 4 channels. The practical upshot is that you round up to the nearest multiple of 4 for the MIC_ARRAY_NUM_MICS define. For example, we use 7 mics on our reference platform but define 8.

Your suggestion of a runtime assertion (or even a simple compile time check for MIC_ARRAY_NUM_MICS % 4 == 0) is s good one. The docs should also be clearer about this. This has now been logged as a github issue so is now tracked and reported on internally.

Thanks again.

**Comment by andrewstanfordjason** [comment]
I have added a compile time check to force the number of microphones to a multiple of 4. This means that memory must be allocated for all 4 channels a if they were all in use. This should solve memory corruption problems. If they persist then please file a bug with an example and i'll get on it.
