### ISSUE TITLE
Silent fail with incorrect PDM data port

### ISSUE THREAD

**Issue by xross** [xmos/lib_mic_array#40]
If you pass in a 4-bit port as the PDM data port (p_pdm_mics) no error or warning is produced. 

The library continues to operate, but returns values at half the speed - possibly breaking timing of other parts of the system and taking a while to track down.

One option would be to raise an exception on an incorrect resource ID for example (ideally tools would allow for this checking)

**Comment by andrewstanfordjason** [comment]
done
