### ISSUE TITLE
Sound quality issue on circular board

### ISSUE THREAD

**Issue by andrewxcav** [xmos/lib_mic_array#62]
The latest version of lib_mic_array  (3.1.1rc1) sounds glitchy on the circular 1v3 mic array board.  Reverting the files:
* src/fir/fir_coeffs.h
* src/fir/fir_coeffs.xc

to commit: 6aefbd9990b7e624b24e47c535d1ccb1d4fb8989 fixes the issue.

The sound quality problems have only been observed on the circular mic array board.

**Comment by andrewstanfordjason** [comment]
On what hardware?

**Comment by andrewxcav** [comment]
xCORE MICROPHONE ARRAY
XP-USB-MIC-UF216
version 1.3

round Ethernet mic array with Akustika mics.

**Comment by andrewstanfordjason** [comment]
My guess is that that PLL setup is set to configure the PLL for the other PLL(on all other boards).

**Comment by andrewstanfordjason** [comment]
If you could attache a project then I'll try to reproduce the failure here. Thanks

**Comment by andrewxcav** [comment]
It happens in AN00128 as well as in our project which specifically configures the PLL for the 3 boards we support.

I'll work on getting you a project in a concise form...

**Comment by andrewxcav** [comment]
I would just run AN00218 at HEAD and at 923dc4d

You will hear an immediate difference in sound quality. Seems to get worse with run time and input volume.

**Comment by andrewxcav** [comment]
This is low priority, but Github doesn't seem to support that kind of thing ;-)
