### ISSUE TITLE
MIC_ARRAY_FIXED_GAIN cannot be set to negative value

### ISSUE THREAD

**Issue by ThomasGmeinder** [xmos/lib_mic_array#79]
I'm setting 
#define MIC_ARRAY_FIXED_GAIN -2
in mic_array_conf.h as per the documentation:
Optionally, mic_array_conf.h may define.....
MIC_ARRAY_FIXED_GAIN
If this define will apply a fixed gain to the 64 bit output of the final stage decimation FIR. The define should be set to an integer between -32 and +32. 

The goal is to reduce the gain on the input signal in an application where clipping is observed.

But setting to -2 produces a compile error:
Analyzing decimate_to_pcm_4ch.S
/Users/thomas/dev/Releases/sw_vocalfusion-[sw]_1.1.2/lib_mic_array/lib_mic_array/src/decimate_to_pcm_4ch.S:437: Error: A00048 Immediate out of range for instruction: 'ldc'.  Value is -2. Allowed ranges are: 0..63, 0..65535.
ERROR: Unable to open elf file '/var/folders/81/fvtc03bn6mvc1c5f801qly7m0000gp/T//cc6uEyM0.o' for loading
xmake[1]: *** [.build_1i1o2_cir43_reduce_gain/_l_mic_array/src/decimate_to_pcm_4ch.S.pca.xml.decouple] Error 1
xmake: *** [analyze] Error 2

**Comment by astewart-xmos** [comment]
Stale
